export const PHILIPS_HUE_CLICK = 'PHILIPS_HUE_CLICK';
export const HOME_SCREEN = 'HOME_SCREEN';
export const PHILIPS_HUE_SCREEN = 'PHILIPS_HUE_SCREEN';
export const ADD_LIGHT_SCREEN = 'ADD_LIGHT_SCREEN';
